### ISSUE TITLE
unable to scroll the timeline after clicking event in the timeline

### ISSUE THREAD

**Issue by engerm** [L4GG/timeline#40] opened 2017-05-11 03:47 UTC
The timeline can be dragged/scrolled to scan events; the 4-arrow cursor is available at this time. If a user clicks on an event in the timeline after dragging/scrolling the time, the user is unable to redrag/rescoll again. The 4-arrow cursor is no longer available.

Tested in Chrome on a Mac.

**Comment by sgeofrank** [comment] 2017-05-11 20:58
Unable to reproduce chrome on Windows 10, can another Mac user confirm?

**Comment by engerm** [comment] 2017-05-11 21:14
I just rechecked and it is NOT doing it for me now.

**Comment by sgeofrank** [comment] 2017-05-11 21:34
Closing for now, I think the performance upgrades may have fixed it.

**Closed** 2017-05-11 21:34 UTC
Labels: needs-confirmation, priority-low
